import {
    Plus,
    Trash2,
    FileText,
    Sparkles,
    ChevronRight,
    ArrowLeft,
    CheckCircle2,
    AlertCircle,
    LayoutDashboard,
    MessageSquare,
    History,
    TrendingUp,
    Target,
    FileCheck,
    AlertTriangle,
    Lightbulb,
    Zap,
    Layout,
    Pencil,
    BarChart3,
    FolderOpen,
    Lock,
    Mail,
    Send,
    Copy,
    User,
    LogOut,
    Settings,
    Loader2
} from 'lucide-react';

export const Icons = {
    Plus,
    Trash: Trash2,
    File: FileText,
    Magic: Sparkles,
    ChevronRight,
    Back: ArrowLeft,
    Check: CheckCircle2,
    Error: AlertCircle,
    Dashboard: LayoutDashboard,
    Message: MessageSquare,
    History,
    Chart: TrendingUp,
    Target,
    FileCheck,
    Warning: AlertTriangle,
    Idea: Lightbulb,
    Fast: Zap,
    Layout,
    Edit: Pencil,
    BarChart: BarChart3,
    Folder: FolderOpen,
    Lock,
    Mail,
    Send,
    Copy,
    User,
    LogOut,
    Settings,
    Spinner: Loader2
};
